version: 2.1
workflows:
  scheduled:
    triggers:
      - schedule:
          cron: "*/15 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - get-me-an-appointment
jobs:
  get-me-an-appointment:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run:
          name: Install deps
          command: npm i
      - run:
          name: Find appointments
          command: node index.js
      - store_artifacts:
          path: ./state.png
