version: 2.1
workflows:
  scheduled:
    triggers:
      - schedule:
          cron: "0,15,40,45 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - get-me-an-appointment
jobs:
  get-me-an-appointment:
    machine:
      image: "ubuntu-1604:201903-01"
    steps:
      - checkout
      - run:
          name: Install node 14
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 14
            nvm alias default 14
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run:
          name: Install deps
          command: npm i
      - run:
          name: Find appointments
          command: node index.js
      - store_artifacts:
          path: ./state.png
